### ISSUE TITLE
character coding problem

### ISSUE THREAD

**Issue by csempe17** [zsiki/ls#2]
The plugin generates an error message if a directory or file name contains special characters. (e.g. ascii 128+)

**Comment by csempe17** [comment]
This probleme is solved in the Batch Plotting dialog. After some testing this bug will be correct in the rest of the plugin.

**Comment by edips** [comment]
Unfortunately I got this error while I imported rw5 format fieldbook:

Traceback (most recent call last):
  File "C:/Users/edips/.qgis2/python/plugins\SurveyingCalculation\surveying_calculation.py", line 353, in load_fieldbook
    self.log.write_log(tr("Fieldbook loaded: ") + fname)
  File "C:/Users/edips/.qgis2/python/plugins\SurveyingCalculation\resultlog.py", line 77, in write_log
    self.write(d + " - " + msg)
  File "C:/Users/edips/.qgis2/python/plugins\SurveyingCalculation\resultlog.py", line 58, in write
    f.write(msg + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0130' in position 47: ordinal not in range(128)

**Comment by zsiki** [comment]
Dear edips,
thanks for your report, it is known issue we could not solve yet :(

**Comment by edips** [comment]
Dear Zsiki, I think this is not a problem. Point files can be copied-pasted in non-included special paths like c://. Thanks for this useful plug-in.
